'use client';

interface DailyBriefingProps {
  briefing: string | null;
  loading: boolean;
  onClose: () => void;
}

export default function DailyBriefing({ briefing, loading, onClose }: DailyBriefingProps) {
  if (!loading && !briefing) return null;

  const renderContent = (text: string) => {
    return text.split('\n').filter(line => line.trim()).map((line, i) => {
      const isBullet = line.trim().startsWith('•') || line.trim().startsWith('-');
      const isNumbered = /^\d+\./.test(line.trim());
      const isBold = line.includes('**');

      if (isBullet) {
        return (
          <li key={i} className="ml-4 text-sm" style={{ color: 'var(--text)' }}>
            {line.replace(/^[•\-]\s*/, '')}
          </li>
        );
      }

      if (isNumbered) {
        const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong style="color: var(--gold)">$1</strong>');
        return (
          <p key={i} className="text-sm mt-3" dangerouslySetInnerHTML={{ __html: formatted }} />
        );
      }

      if (isBold) {
        const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong style="color: var(--gold)">$1</strong>');
        return (
          <p key={i} className="text-sm mt-2" dangerouslySetInnerHTML={{ __html: formatted }} />
        );
      }

      return (
        <p key={i} className="text-sm mt-2" style={{ color: 'var(--text)' }}>
          {line}
        </p>
      );
    });
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(4px)' }}
      onClick={onClose}
    >
      <div
        className="card w-full max-w-2xl max-h-[85vh] overflow-y-auto animate-fade-in"
        onClick={e => e.stopPropagation()}
      >
        <div
          className="sticky top-0 flex items-center justify-between p-4 border-b border-[var(--border)]"
          style={{ background: 'var(--surface)' }}
        >
          <div className="flex items-center gap-3">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center text-sm"
              style={{ background: 'var(--gold)', color: '#0a0b0d' }}
            >
              ⚡
            </div>
            <div>
              <h2 className="text-sm font-bold" style={{ color: 'var(--gold)' }}>Daily Briefing</h2>
              <p className="mono text-[10px]" style={{ color: 'var(--text-muted)' }}>
                AI-generated · {new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })}
              </p>
            </div>
          </div>
          <button onClick={onClose} className="btn-ghost text-xs px-3 py-1.5">
            ✕ Close
          </button>
        </div>

        <div className="p-6">
          {loading ? (
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <span
                  className="w-5 h-5 border-2 border-t-transparent rounded-full animate-spin"
                  style={{ borderColor: 'var(--gold)', borderTopColor: 'transparent' }}
                />
                <span className="mono text-xs" style={{ color: 'var(--gold)' }}>
                  Generating your morning briefing…
                </span>
              </div>
              {[...Array(5)].map((_, i) => (
                <div key={i} className="h-3 rounded animate-pulse" style={{ background: 'var(--border)', width: `${70 + Math.random() * 30}%` }} />
              ))}
            </div>
          ) : briefing ? (
            <div className="space-y-1 leading-relaxed">
              {renderContent(briefing)}
            </div>
          ) : null}
        </div>

        {!loading && briefing && (
          <div
            className="sticky bottom-0 p-4 border-t border-[var(--border)] flex justify-between items-center"
            style={{ background: 'var(--surface)' }}
          >
            <p className="mono text-[10px]" style={{ color: 'var(--text-muted)' }}>
              Generated by Claude · For informational purposes only
            </p>
            <button
              onClick={() => navigator.clipboard?.writeText(briefing)}
              className="btn-ghost text-xs"
            >
              Copy
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
